version: "3.7"

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/mnt/app
    restart: always
    links:
      - redis
    networks:
      - node_net

  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    hostname: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    volumes:
      - ./redis/data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      node_net:
        ipv4_address: 172.28.1.4