version: "3.7"

networks:
  crawler:
    external: true

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/mnt/app
    restart: always
    links:
      - redis
    networks:
      - crawler

  redis:
    image: redis:4.0
    container_name: crawler_app
    restart: always
    hostname: redislocal
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
    volumes:
      - ./redis/data:/data
    ports:
      - "127.0.0.1:6382:6379"
    networks:
      - crawler